<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>WebApp</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>WebApp</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JasperFx" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
  </ItemGroup>

</Project>
