<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Alba\Alba.csproj" />
    <ProjectReference Include="..\IdentityServer.New\IdentityServer.New.csproj" />
    <ProjectReference Include="..\WebAppSecuredWithJwt\WebAppSecuredWithJwt.csproj" />
    <ProjectReference Include="..\WebApp\WebApp.csproj" />
    <ProjectReference Include="..\WebApiAspNetCore3\WebApiStartupHostingModel.csproj" />
    <ProjectReference Include="..\WebApiNet6\WebApiNet6.csproj" />
    <ProjectReference Include="..\MinimalApiWithOakton\MinimalApiWithOakton.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JasperFx" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
    <PackageReference Include="Verify.AspNetCore" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="TestImage.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TestTextFile.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Samples\SnapshotTesting.SnapshotTest.DotNet10_0.verified.txt">
      <DependentUpon>SnapshotTesting.cs</DependentUpon>
    </None>
  </ItemGroup>


</Project>